name: dlp-cpu-latest
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - jupyterlab
  - notebook
  - ipython
  - ipywidgets
  - matplotlib
  - numpy
  - pandas
  - pillow
  - scikit-learn
  - scipy
  - requests
  - tqdm
  - seaborn
  - graphviz
  - python-graphviz
  - pydot
  - pip:
    # Latest Keras 3
    - keras
    # Latest TensorFlow (CPU)
    - tensorflow
    # Latest PyTorch (CPU)
    - torch
    - torchvision
    - torchaudio
    # Latest JAX (CPU)
    - jax
    - jaxlib
    # Other useful packages
    - kagglehub
    - tensorflow-datasets
    - tensorflow-hub
    - transformers
    - tokenizers
    - datasets
    - accelerate
    - gradio
    - wandb
    # Interpretability
    - shap
